# Mini-Report Rubric, Tiny Earth Genomics

## General Notes

- Write your report in *full sentences*, especially to demonstrate reasoning and understanding
- Assume the reader knows nothing about the lab (so you can demonstrate what you understand about it)
- Use your own words. Do not plagiarize your colleagues or copy/paste from the protocol - Type your report (I will not accept hand-written assignments) and submit through Canvas if possible. Make sure that your report is neatly and logically laid out
- The report should be a cohesive piece of writing that could be read all together, with paragraphs following on logically. Don't make it look like a list of separate items cobbled together to satisfy the rubric
- Do not leave anything out. If your understanding is not apparent from the words you have written, I can't assume what is in your mind 
- Before handing the lab report in, use this rubric like a check list. Go through each item in turn and ask yourself, "did I address this item fully?" Every year students loose easy points by simply not checking their work against the rubric. If there is a part you don't understand, such as "passive voice" or "past tense", please ask.

- Late reports will receive a zero grade.

## Name:

| Comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | Total   |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------|
| Introduction including hypothesis (20%)  Briefly summarize what was done in the  lab (10%)  State a hypothesis of what the expected  results would be if the procedure is  successful, then whether results  supported the hypothesis (10%) Materials and methods (20%)  Methods are written in full sentences  (own words), using past tense and  passive voice (5%)  Details of programs/procedures used  for analyses, along with details such  as run parameters (5%)  Deviations from the handbook protocol  accurately noted (i.e. what you did  rather than what the protocol called  for) (5%) |         |

| Comments                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Total                                                                         |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
|                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Section includes enough information for  someone to repeat the procedure (5%) |
| Results (40%)  Figures captioned accurately and clearly  (14%)  Clear description of results provided in  text (14%)  Results written in logical format (writer  understands how analyses connect to  one another (7%)  Results written in own words (5%) Discussion and conclusions (20%)  Briefly summarize what was done (5%)  Contextualize results with literature  (10%)  Literature cited [must include journal  articles, journal reviews or book  chapters] (5%) |                                                                               |
